### ISSUE TITLE
Support for Gremlin in .NET Core

### ISSUE THREAD

**Issue by Crokus** [Azure-Samples/azure-cosmos-db-graph-dotnet-getting-started#1]
[Microsoft.Azure.Graphs 0.2.0-preview](https://www.nuget.org/packages/Microsoft.Azure.Graphs/) package supports only full .NET Framework thus it's not possible to work with Comsos DB Graphs on .NET Core. 
Is there any timeframe on .NET Core support for Gremlin traversal language?

**Comment by csharpsi** [comment]
The Microsoft.Azure.Graphs 0.2.0-preview package is also not supported in VS2017 in a new ASP.NET Framework Project either

**Comment by Confusingboat** [comment]
+1

**Comment by papa-pep** [comment]
+1

**Comment by syedhassaanahmed** [comment]
+1

**Comment by RichardGrundy** [comment]
Any news on this? With .Net Core 2.0 is released I would assume the port will be easier now? How about source code release so we can help get the work done?

**Comment by BlitzkriegSoftware** [comment]
+1 Please make this work in .NET Core 2 ASAP!

**Comment by scamp81** [comment]
+1

**Comment by A100K** [comment]
+1

**Comment by syedhassaanahmed** [comment]
Seems like [Microsoft.Azure.Graphs](https://www.nuget.org/packages/Microsoft.Azure.Graphs/) was updated 2 days ago with .NET Core support! .. I've put together a .NET Core port of this sample here with the updated SDK.

https://github.com/syedhassaanahmed/azure-cosmos-db-graph-dotnet-core

**Comment by matthewbcline** [comment]
So it looks like the 0.3.0-preview does _not_ support .NET Core 2. Seriously?!?

**Comment by syedhassaanahmed** [comment]
@matthewbcline Not sure what you mean by "does not support .NET Core 2." .. The above sample I posted compiles against .NET Core 2.0.

**Comment by matthewbcline** [comment]
@syedhassaanahmed It's not about your sample. The library itself hangs when I run it on .NET Core v2. Apologies if that wasn't clear.

Looks like the assembly causing the conflict is `Microsoft.Logging.Extensions.Console` version 2.0.0.

**Comment by olivertowers** [comment]
@matthewbcline The CosmosDB Graph sample in this repo was rewritten to work with .NET Core 2.0 and appears to be building and running without any errors. Does the sample work for you or is this specific to your .NET Core project? Are you able to share your .csproj file so I can look into this further?

**Comment by matthewbcline** [comment]
@olivertowers -- sorry for the delay getting back to you, was on vacation.

The `Microsoft.Azure.Graphs` library doesn't work with `Microsoft.Extensions.Logging.Console` version 2.0.0. 

I can't send you my csproj but I can describe it. I'm doing a simple console app. Have added logging with this block in `Main()`:

```
var services = new ServiceCollection();
var loggerFactory = new LoggerFactory().AddConsole(LogLevel.Trace, true);
services.AddSingleton(loggerFactory);
services.AddLogging();
```

The console app hangs on run if I use version 2.0.0 of `Microsoft.Extensions.Logging.Console`. The app works fine if I use version 1.1.2.

**Comment by olivertowers** [comment]
@matthewbcline - I was unable to repro the issue you described. I used the sample project to try and made the following modifications in my attempt:

Add packagereferences to 2.0.0 of `Microsoft.Extensions.Logging.Console` + additional package updates.

```
    <PackageReference Include="Microsoft.Azure.Graphs" Version="0.3.0-preview" />
    <PackageReference Include="Microsoft.Extensions.DependencyInjection" Version="2.0.0" />
    <PackageReference Include="Microsoft.Extensions.Logging.Console" Version="2.0.0" />
    <PackageReference Include="Microsoft.Extensions.Configuration.Json" Version="2.0.0" />
```

Including the code snippet in Program.cs + some logging operations to ensure that console logger is exercised:

```
            var services = new ServiceCollection();
            var loggerFactory = new LoggerFactory().AddConsole(LogLevel.Trace, true);
            services.AddSingleton(loggerFactory);
            services.AddLogging();

            var serviceProvider = services.BuildServiceProvider();

            var logger = serviceProvider.GetService<ILoggerFactory>()
                .CreateLogger<Program>();

            logger.LogInformation("Starting application");
```
This was built targeting netcoreapp2.0 and ran with VS and dotnet CLI without hanging

Is there anything additional you can share?

**Comment by matthewbcline** [comment]
@olivertowers -- trying to reproduce this from pre-vacation, bear with me. At one point I was able to reproduce a hang, but am not seeing that any more.

I am using the Cosmos DB emulator to develop locally.

Here is my `Main()` method:

```
static void Main(string[] args)
{
    var services = new ServiceCollection();
    var loggerFactory = new LoggerFactory().AddConsole(LogLevel.Trace, true);
    services.AddSingleton(loggerFactory);
    services.AddLogging();

    var serviceProvider = services.BuildServiceProvider();

    var logger = serviceProvider.GetService<ILoggerFactory>()
        .CreateLogger<Program>();

    logger.LogInformation("Starting application");

    var documentClient = new DocumentClient(
        new Uri("https://localhost:8081"),
        "C2y6yDjf5/R+ob0N8A7Cgv30VRDJIWEHLM+4QDU5DE2nQ9nDuVTqobD4b8mGGyPMbIZnqyMsEcaGQy67XIw/Jw==",
        new ConnectionPolicy { ConnectionMode = ConnectionMode.Direct, ConnectionProtocol = Protocol.Tcp });

    documentClient.OpenAsync().Wait();

    documentClient.CreateDatabaseIfNotExistsAsync(new Database() { Id = "foodb" }).Wait();

    var documentCollection = documentClient.CreateDocumentCollectionIfNotExistsAsync(
        UriFactory.CreateDatabaseUri("foodb"),
        new DocumentCollection { Id = "foo" },
        new RequestOptions { OfferThroughput = 1000 }).Result;

    var gremlinQuery = $@"g.addV('bar').property('id', 'bar.{Guid.NewGuid()}')";

    logger.LogDebug($"Issuing Gremlin command:\n{gremlinQuery}");
    var query = documentClient.CreateGremlinQuery<dynamic>(documentCollection, gremlinQuery);
    query.ExecuteNextAsync().Wait();
}
```

This method produces the following exception when I call `documentClient.CreateGremlinQuery`:

```
System.TypeInitializationException occurred
  HResult=0x80131534
  Message=The type initializer for 'Microsoft.Azure.Graphs.GraphExtensions' threw an exception.
  Source=<Cannot evaluate the exception source>
  StackTrace:
   at Microsoft.Azure.Graphs.GraphExtensions.CreateGremlinQuery[T](DocumentClient documentClient, DocumentCollection collection, String gremlinExpression, FeedOptions feedOptions, GraphSONMode graphSONMode)
   at GraphConsoleTest.Program.Main(String[] args) in c:\git\GraphConsoleTest\GraphConsoleTest\Program.cs:line 43

Inner Exception 1:
TypeLoadException: Method 'get_Properties' in type 'Microsoft.Extensions.Configuration.ConfigurationBuilder' from assembly 'Microsoft.Extensions.Configuration, Version=1.1.2.0, Culture=neutral, PublicKeyToken=adb9793829ddae60' does not have an implementation.
```

Note the version of `Microsoft.Extensions.Configuration` in the error message; this is not a 2.0 version. I also see that the CSPROJ from the sample has an explicit reference to version 1.1.2 of this package.

I believe - but am not 100% sure - that I tried to explicitly install `Microsoft.Extensions.Configuration` version 2.0.0, and this produced the hang.

**Comment by Tameshiwari** [comment]
I was unable to repro the issue you described. I used the sample project to try and made the following modifications in my attempt:

Hi Oliver,
I've taken your approach in **dotnet CLI Core 2.**0 through **Visual Studio Code** and can confirm it worked in my case.
Now I'm facing an issue with  double negative value [such as in declaring longitude...] and was wondering if anyone can give me a hint. If I enter following: 

`g.addV('airport').property('id', 'YUL').property('latitude', 45.4706001282).property('longitude', -73.7407989502)`

So no matter if I specify a minus (-) prefix double value it seems that Vertex conversion doesn't take it in consideration and I will always end up with positive value no matter what. 
So what I would expect to see is:

`"longitude": [
        {
          "id": "bdce9642-4744-4d0b-8a28-16b82edd7fec",
          "value": -73.7407989502 <----
        }
      ]
`
though final result ends up as follows:

`longitude": [
        {
          "id": "bdce9642-4744-4d0b-8a28-16b82edd7fec",
          "value": 73.7407989502 <---- minus prefix is missing...
        }
      ]`

Any hint on how to solve that would be deeply appreciated. Thank you.
