### ISSUE TITLE
Error reading JObject from JsonReader. Path ''

### ISSUE THREAD

**Issue by jeff-bacon** [Azure-Samples/azure-cosmos-db-graph-dotnet-getting-started#9]
Getting the exception below when trying to debug in Visual Studio 2017.  Throws on this line:

Database database = await client.CreateDatabaseIfNotExistsAsync(new Database { Id = "graphdb" });

System.AggregateException
  HResult=0x80131500
  Message=One or more errors occurred.
  Source=mscorlib
  StackTrace:
   at System.Threading.Tasks.Task.ThrowIfExceptional(Boolean includeTaskCanceledExceptions)
   at System.Threading.Tasks.Task.Wait(Int32 millisecondsTimeout, CancellationToken cancellationToken)
   at System.Threading.Tasks.Task.Wait()
   at azure-cosmos-db-graph-dotnet-getting-started-master\GraphGetStarted\Program.cs:line 43

Inner Exception 1:
JsonReaderException: Error reading JObject from JsonReader. Path '', line 0, position 0.

**Comment by NikolaiTsepalov** [comment]
Sample app has an incorrect setting is the App.config.
Instead of the 
<add key="Endpoint" value="https://MY_DB.gremlin.cosmosdb.azure.com:443/"/>
it should be
<add key="Endpoint" value="https://MY_DB.documents.azure.com:443/"/>

To make sure you have correct settings,  go to your DB on Azure > Settings > Keys > Read-write Keys
Check the URL and  PRIMARY KEY fields

**Comment by jeff-bacon** [comment]
That did the trick!  Thanks.
